pub const TICKS_PER_HOUR: u64 = 1;
pub const TICKS_PER_DAY: u64 = 24 * TICKS_PER_HOUR;
pub const TICKS_PER_WEEK: u64 = 7 * TICKS_PER_DAY;
pub const TICKS_PER_YEAR: u64 = 365 * TICKS_PER_DAY;

pub const REPRODUCTIVE_AGE_START: u64 = 18 * TICKS_PER_YEAR;
pub const FEMALE_REPRODUCTIVE_AGE_END: u64 = 55 * TICKS_PER_YEAR;
pub const MALE_REPRODUCTIVE_AGE_END: u64 = 70 * TICKS_PER_YEAR;
pub const GESTATION_TICKS: u64 = 40 * TICKS_PER_WEEK;
pub const POSTPARTUM_TICKS: u64 = 180 * TICKS_PER_DAY;

pub const FOUNDER_AGE_MIN: u64 = REPRODUCTIVE_AGE_START;
pub const FOUNDER_AGE_MAX: u64 = 40 * TICKS_PER_YEAR;
pub const BASE_LIFESPAN_TICKS: u64 = 800_000;
pub const LIFESPAN_VARIATION_TICKS: u64 = 150_000;

pub fn years_from_ticks(ticks: u64) -> f64 {
    ticks as f64 / TICKS_PER_YEAR as f64
}

pub const INFANT_AGE_END: u64 = 3 * TICKS_PER_YEAR;
pub const CHILD_AGE_END: u64 = 12 * TICKS_PER_YEAR;
pub const ADOLESCENT_AGE_END: u64 = 18 * TICKS_PER_YEAR;
pub const ELDER_AGE_START: u64 = 65 * TICKS_PER_YEAR;
